config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  resources :students
  resources :exams
  resources :teachers
  resources :reports
  resources :payments
  resources :pockets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exam.rb
class Exam < ApplicationRecord
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/pocket.rb
class Pocket < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord

  def self.getKelas 
    arrayKelas = ['Kelas X', 'Kelas XI', 'Kelas XII']
    result = []
    arrayKelas.each do |kelas|
      result.push([kelas, kelas])
    end
    result
  end
end

app/models/teacher.rb
class Teacher < ApplicationRecord

def self.getGuruAndNik 
  teachers = self.all
  result = []
  teachers.each do |teacher| 
    result.push([teacher.name, teacher.nik])
  end
  result
end

end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  def index
    @exams = Exam.all
  end

  def new
    @exam = Exam.new
  end

  def create
    @exam = Exam.new(student_params)
    @exam.save
    flash[:notice] = "Data Berhasil di Simpan."
    redirect_to exams_path
  end

  def show
    id = params[:id]
    @exam = Exam.find(id)
  end

  def edit
    id = params[:id]
    @exam = Exam.find(id)
  end

  def update
    id = params[:id]
    exam = Exam.find(id)
    exam.update(student_params)  
    flash[:notice] = "Data Berhasil di Update."
    redirect_to exam_path(id)
  end

  def destroy
    id = params[:id]
    exam = Exam.find(id)
    exam.destroy
    flash[:notice] = "Data Berhasil di Hapus."
    redirect_to exams_path
  end

  private

  def student_params
    params.require(:exam).permit(:title, :mapel, :duration, :nilai, :active_status, :level, :student_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def index
  end

  def new
  end

  def show
  end

  def edit
  end
end

app/controllers/pockets_controller.rb
class PocketsController < ApplicationController
  def index
  end

  def new
  end

  def show
  end

  def edit
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
  end

  def new
  end

  def show
  end

  def edit
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def new
    @student = Student.new
    @kelas = Student.getKelas
  end

  def create
    @student = Student.new(student_params)
    @student.save
    flash[:notice] = "Data Berhasil di Simpan."
    redirect_to students_path
  end

  def show
    id = params[:id]
    @student = Student.find(id)
  end

  def edit
    id = params[:id]
    @student = Student.find(id)
    @kelas = Student.getKelas
  end

  def update
    id = params[:id]
    student = Student.find(id)
    student.update(student_params)  
    flash[:notice] = "Data Berhasil di Update."
    redirect_to student_path(id)
  end

  def destroy
    id = params[:id]
    student = Student.find(id)
    student.destroy
    flash[:notice] = "Data Berhasil di Hapus."
    redirect_to students_path
  end

  private

  def student_params
    params.require(:student).permit(:name, :username, :age, :kelas, :address, :city, :nik)
  end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def index
  end

  def new
  end

  def show
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/pockets_helper.rb
module PocketsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/exams/edit.html.erb
<div class="container">
  <center><h2>Kejar V4</h2></center>
  <br>
  <%= link_to 'Kembali', exams_path, class: 'btn btn-primary' %>
  <br>
  <br>
  <div class="card">
    <div class="card-header">
     Edit Exam
    </div>
    <div class="card-body">
    <%= form_for(@exam) do |f| %>
        <div class="form-group">
          <%= f.label :title, class: "form-label" %>
          <%= f.text_field :title, class: "form-control col-md-4", required: true  %>
        </div>

        <div class="form-group">
          <%= f.label :mapel, class: "form-label" %>
          <%= f.text_field :mapel, class: "form-control col-md-4", required: true  %>
        </div>

        <div class="form-group">
          <%= f.label :duration, class: "form-label" %>
          <%= f.text_field :duration, class: "form-control col-md-4", required: true  %>
        </div>

        <div class="form-group">
          <%= f.label :nilai, class: "form-label" %>
          <%= f.text_field :nilai, class: "form-control col-md-4", required: true  %>
        </div>

        <div class="form-group">
          <%= f.label :active_status, class: "form-label" %>
          <%= f.text_field :active_status, class: "form-control col-md-4", required: true  %>
        </div>

        <div class="form-group">
          <%= f.label :level, class: "form-label" %>
          <%= f.text_field :level, class: "form-control col-md-4", required: true  %>
          <%# <%= select_tag(:nik, options_for_select(@teacherList), class: "form-control col-md-4") %>
        </div>

        <div class="form-group">
          <%= f.label :student_id, class: "form-label" %>
          <%= f.text_field :student_id, class: "form-control col-md-4", required: true  %>
        </div>

        <%= f.submit "Save", class: "btn btn-primary" %>
    <% end %>
    </div>
    <br>
</div>

app/views/exams/index.html.erb
<div class="container">
  <center><h2>Kejar Ver. Alpha</h2></center>
  <br>
  <h3>List Siswa</h3>
  <br>
    <% if flash[:notice] %>
      <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
      </div>
    <% end %>
  <table class="table table-bordered">
    <thead class="thead-light">
      <tr>
        <th scope="col">Title</td>
        <th scope="col">Mapel</td>
        <th scope="col">Duration</td>
        <th scope="col">Nilai</td>
        <th scope="col">Active Status</td>
        <th scope="col">Level</td>
        <th colspan="3" scope="col">Action</td>
      </tr>
    </thead>
    <tbody>
      <% @exams.each do |exam| %>
      <tr>
        <td><%= exam.title %></td>
        <td><%= exam.mapel %></td>
        <td><%= exam.duration %></td>
        <td><%= exam.nilai %></td>
        <td><%= exam.active_status %></td>
        <td><%= exam.level %></td>
        <td><%= link_to 'Detail', exam_path(exam.id) %></td>
        <td><%= link_to 'Hapus', exam_path(exam.id), :method => :delete, :data => {:confirm => 'Are you sure?'} %></td>
        <td><%= link_to 'Edit', edit_exam_path(exam.id) %></td>
      </tr>
      <% end %>
      <% if @exams.length < 1 %>
        <tr>
          <td colspan="9"><center>Data Kosong.</center> </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <td><%= link_to 'New Exam', new_exam_path, class: 'btn btn-primary' %></td>
</div>

app/views/exams/new.html.erb
<div class="container">
  <center><h2>Kejar V4</h2></center>
  <br>
  <%= link_to 'Kembali', students_path, class: 'btn btn-primary' %>
  <br>
  <br>
  <div class="card">
    <div class="card-header">
     Add New Exam
    </div>
    <div class="card-body">
    <%= form_for(@exam) do |f| %>
        <div class="form-group">
          <%= f.label :title, class: "form-label" %>
          <%= f.text_field :title, class: "form-control col-md-4", required: true  %>
        </div>

        <div class="form-group">
          <%= f.label :mapel, class: "form-label" %>
          <%= f.text_field :mapel, class: "form-control col-md-4", required: true  %>
        </div>

        <div class="form-group">
          <%= f.label :duration, class: "form-label" %>
          <%= f.text_field :duration, class: "form-control col-md-4", required: true  %>
        </div>

        <div class="form-group">
          <%= f.label :nilai, class: "form-label" %>
          <%= f.text_field :nilai, class: "form-control col-md-4", required: true  %>
        </div>

        <div class="form-group">
          <%= f.label :active_status, class: "form-label" %>
          <%= f.text_field :active_status, class: "form-control col-md-4", required: true  %>
        </div>

        <div class="form-group">
          <%= f.label :level, class: "form-label" %>
          <%= f.text_field :level, class: "form-control col-md-4", required: true  %>
          <%# <%= select_tag(:nik, options_for_select(@teacherList), class: "form-control col-md-4") %>
        </div>

        <div class="form-group">
          <%= f.label :student_id, class: "form-label" %>
          <%= f.text_field :student_id, class: "form-control col-md-4", required: true  %>
        </div>

        <%= f.submit "Save", class: "btn btn-primary" %>
    <% end %>
    </div>
    <br>
</div>

app/views/exams/show.html.erb
<div class="container">
  <center><h2>Kejar Ver. Alpha</h2></center>
  <br>
  <% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <div class="card">
    <div class="card-header">
      <h5 class="card-title"><%= @exam.title %></h5>
    </div>
    <div class="card-body">
      <p class="card-text">Mapel: <%= @exam.mapel %> </p>
      <p class="card-text">Nilai: <%= @exam.nilai %> </p>
      <p class="card-text">Status Active: <%= @exam.active_status %> </p>
      <p class="card-text">Level: <%= @exam.level %> </p>
      <p class="card-text">Student ID: <%= @exam.student_id %> </p>
      <%= link_to 'Kembali', exams_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/payments/edit.html.erb
<h1>Payments#edit</h1>
<p>Find me in app/views/payments/edit.html.erb</p>

app/views/payments/index.html.erb
<h1>Payments#index</h1>
<p>Find me in app/views/payments/index.html.erb</p>

app/views/payments/new.html.erb
<h1>Payments#new</h1>
<p>Find me in app/views/payments/new.html.erb</p>

app/views/payments/show.html.erb
<h1>Payments#show</h1>
<p>Find me in app/views/payments/show.html.erb</p>

app/views/pockets/edit.html.erb
<h1>Pockets#edit</h1>
<p>Find me in app/views/pockets/edit.html.erb</p>

app/views/pockets/index.html.erb
<h1>Pockets#index</h1>
<p>Find me in app/views/pockets/index.html.erb</p>

app/views/pockets/new.html.erb
<h1>Pockets#new</h1>
<p>Find me in app/views/pockets/new.html.erb</p>

app/views/pockets/show.html.erb
<h1>Pockets#show</h1>
<p>Find me in app/views/pockets/show.html.erb</p>

app/views/reports/edit.html.erb
<h1>Reports#edit</h1>
<p>Find me in app/views/reports/edit.html.erb</p>

app/views/reports/index.html.erb
<h1>Reports#index</h1>
<p>Find me in app/views/reports/index.html.erb</p>

app/views/reports/new.html.erb
<h1>Reports#new</h1>
<p>Find me in app/views/reports/new.html.erb</p>

app/views/reports/show.html.erb
<h1>Reports#show</h1>
<p>Find me in app/views/reports/show.html.erb</p>

app/views/students/edit.html.erb
<div class="container">
  <center><h2>Kejar Ver. Alpha</h2></center>
  <br>
  <%= link_to 'Kembali', students_path, class: 'btn btn-primary' %>
  <br>
  <br>
  <div class="card">
    <div class="card-header">
     Edit Student
    </div>
    <div class="card-body">
    <%= form_for(@student) do |f| %>
        <div class="form-group">
          <%= f.label :name, class: "form-label" %>
          <%= f.text_field :name, class: "form-control col-md-4", required: true  %>
        </div>

        <div class="form-group">
          <%= f.label :username, class: "form-label" %>
          <%= f.text_field :username, class: "form-control col-md-4", required: true  %>
        </div>

        <div class="form-group">
          <%= f.label :age, class: "form-label" %>
          <%= f.text_field :age, class: "form-control col-md-4", required: true  %>
        </div>

        <div class="form-group">
          <%= f.label :kelas, class: "form-label" %>
          <%= f.text_field :kelas, class: "form-control col-md-4", required: true  %>
        </div>

        <div class="form-group">
          <%= f.label :address, class: "form-label" %>
          <%= f.text_field :address, class: "form-control col-md-4", required: true  %>
        </div>

        <div class="form-group">
          <%= f.label :city, class: "form-label" %>
          <%= f.text_field :city, class: "form-control col-md-4", required: true  %>
        </div>

        <div class="form-group">
          <%= f.label 'NIK', class: "form-label" %>
          <%= f.text_field :nik, class: "form-control col-md-4", required: true  %>
          <%# <%= select_tag(:nik, options_for_select(@teacherList), class: "form-control col-md-4") %>
        </div>

        <%= f.submit "Save", class: "btn btn-primary" %>
    <% end %>
    </div>
    <br>
</div>

app/views/students/index.html.erb
<div class="container">
  <center><h2>Kejar Ver. Alpha</h2></center>
  <br>
  <h3>List Siswa</h3>
  <br>
    <% if flash[:notice] %>
      <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
      </div>
    <% end %>
  <table class="table table-bordered">
    <thead class="thead-light">
      <tr>
        <th scope="col">Name</td>
        <th scope="col">Username</td>
        <th scope="col">Age</td>
        <th scope="col">Class</td>
        <th scope="col">Address</td>
        <th scope="col">City</td>
        <th colspan="3" scope="col">Action</td>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.username %></td>
        <td><%= student.age %></td>
        <td><%= student.kelas %></td>
        <td><%= student.address %></td>
        <td><%= student.city %></td>
        <td><%= link_to 'Detail', student_path(student.id) %></td>
        <td><%= link_to 'Hapus', student_path(student.id), :method => :delete, :data => {:confirm => 'Are you sure?'} %></td>
        <td><%= link_to 'Edit', edit_student_path(student.id) %></td>
      </tr>
      <% end %>
      <% if @students.length < 1 %>
        <tr>
          <td colspan="9"><center>Data Kosong.</center> </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <td><%= link_to 'New Student', new_student_path, class: 'btn btn-primary' %></td>
</div>

app/views/students/new.html.erb
<div class="container">
  <center><h2>Kejar V4</h2></center>
  <br>
  <%= link_to 'Kembali', students_path, class: 'btn btn-primary' %>
  <br>
  <br>
  <div class="card">
    <div class="card-header">
     Add New Student
    </div>
    <div class="card-body">
    <%= form_for(@student) do |f| %>
        <div class="form-group">
          <%= f.label :name, class: "form-label" %>
          <%= f.text_field :name, class: "form-control col-md-4", required: true  %>
        </div>

        <div class="form-group">
          <%= f.label :username, class: "form-label" %>
          <%= f.text_field :username, class: "form-control col-md-4", required: true  %>
        </div>

        <div class="form-group">
          <%= f.label :age, class: "form-label" %>
          <%= f.text_field :age, class: "form-control col-md-4", required: true  %>
        </div>

        <div class="form-group">
          <%= f.label :kelas, class: "form-label" %>
          <%= f.text_field :kelas, class: "form-control col-md-4", required: true  %>
        </div>

        <div class="form-group">
          <%= f.label :address, class: "form-label" %>
          <%= f.text_field :address, class: "form-control col-md-4", required: true  %>
        </div>

        <div class="form-group">
          <%= f.label :city, class: "form-label" %>
          <%= f.text_field :city, class: "form-control col-md-4", required: true  %>
        </div>

        <div class="form-group">
          <%= f.label 'NIK', class: "form-label" %>
          <%= f.text_field :nik, class: "form-control col-md-4", required: true  %>
          <%# <%= select_tag(:nik, options_for_select(@teacherList), class: "form-control col-md-4") %>
        </div>

        <%= f.submit "Save", class: "btn btn-primary" %>
    <% end %>
    </div>
    <br>
</div>

app/views/students/show.html.erb
<div class="container">
  <center><h2>Kejar Ver. Alpha</h2></center>
  <br>
  <% if flash[:notice] %>
    <div class="alert alert-success" role="alert">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <div class="card">
    <div class="card-header">
      <h5 class="card-title"><%= @student.name %></h5>
    </div>
    <div class="card-body">
      <p class="card-text">Username: <%= @student.username %> </p>
      <p class="card-text">Age: <%= @student.age %> </p>
      <p class="card-text">Class: <%= @student.kelas %> </p>
      <p class="card-text">Address: <%= @student.address %> </p>
      <p class="card-text">City: <%= @student.city %> </p>
      <p class="card-text">NIK: <%= @student.nik %> </p>
      <%= link_to 'Kembali', students_path, class: 'btn btn-primary' %>
    </div>
  </div>
</div>